# ZSH configuration for all shells.
#
# Environment variable definitions go here, but that's about it. All
# other definitions go into zshrc or lib/plugins.

# Set the path to our shell configuration.
ZSH=$HOME/.dots
DOTS=$ZSH

# Set our shell paths to load from all of the bin's on the machine.
PATH=/usr/local/bin:/usr/local/share/npm/bin:/usr/local/Cellar/python/2.7.1/bin:/usr/local/git/bin:/usr/bin:$HOME/.dots/bin:$HOME/.rvm/bin:$PATH
MANPATH=/opt/local/share/man:$MANPATH

# Text editing and paging
EDITOR='vim'
PAGER='less -R'

# A more basic version of my promptstring for non-interactive shells.
PROMPT="♬  "

# PostgreSQL config
ARCHFLAGS='-arch x86_64'
PGDATA=/usr/local/var/postgres

# Configure the MySQL prompt to show more information.
MYSQL_PS1="\R:\m:\s \h> "

# Define the C compiler as GCC 4.2
CC=/usr/local/bin/gcc-4.2

# Disable weekly automatic update.
DISABLE_AUTO_UPDATE="true"

# Don't set iTerm/Terminal's title automatically.
DISABLE_AUTO_TITLE="true"

# Display red dots when ZSH is hanging.
COMPLETION_WAITING_DOTS="true"

# Load the framework.
source "$ZSH/lib/dots.sh"

# Make Ruby even faster
RUBY_HEAP_MIN_SLOTS=1000000
RUBY_HEAP_SLOTS_INCREMENT=1000000
RUBY_HEAP_SLOTS_GROWTH_FACTOR=1
RUBY_GC_MALLOC_LIMIT=1000000000
RUBY_HEAP_FREE_MIN=500000

# Always use Bundler with RVM.
USE_BUNDLER=force

# Colorize Grep
export GREP_OPTIONS='--color=auto'
export GREP_COLOR='1;32'

# Load interactive shell settings
source ~/.zshrc
