# Plugins
source "$ZSH/lib/dots/antigen.zsh"
antigen-lib
antigen-bundle tubbo/dots lib/plugins/git
antigen-bundle osx
antigen-bundle tubbo/dots lib/plugins/bundler
antigen-bundle tubbo/dots lib/plugins/git-flow
antigen-bundle knife
antigen-bundle zsh-users/zsh-syntax-highlighting
antigen-bundle cap
antigen-bundle tubbo/dots lib/plugins/ruby
antigen-bundle tubbo/dots lib/plugins/rails3

# Prompt string
local path_prompt="%{$reset_color%}%~"
PROMPT="%{$fg[white]%}♬  %{$reset_color%}"
RPROMPT="${path_prompt}"

alias c='clear'
