##
# DOTS
#
# Base ZSH configuration.
##

# Set the path to our shell configuration.
ZSH=$HOME/.dots
DOTS=$ZSH

# Set our shell paths to load from all of the bin's on the machine.
PATH=/usr/local/share/npm/bin:/usr/local/Cellar/python/2.7.1/bin:/usr/local/git/bin:/usr/bin:/usr/local/bin:$HOME/.dots/bin:$HOME/.rvm/bin:$PATH
MANPATH=/opt/local/share/man:$MANPATH

# Set MacVim as our catault text editor, with switches to support Git.
EDITOR='mvim -f --nomru'

# Default text editor
#EDITOR='mvim -f --nomru -c "au VimLeave * !open -a Terminal"'
EDITOR='vim'

# PostgreSQL config
ARCHFLAGS='-arch x86_64'
PGDATA=/usr/local/var/postgres

# Configure the MySQL prompt to show more information.
MYSQL_PS1="\R:\m:\s \h> "

# Define the C compiler as GCC 4.2
CC=/usr/bin/gcc-4.2

# Keep everything case-insensitive.
#CASE_SENSITIVE="true"

# Disable weekly automatic update.
DISABLE_AUTO_UPDATE="true"

# Use colors in `ls`
#DISABLE_LS_COLORS="true"

# Don't set iTerm/Terminal's title automatically.
#DISABLE_AUTO_TITLE="true"

# Display red dots when ZSH is hanging.
COMPLETION_WAITING_DOTS="true"

# Load plugins
plugins=(git osx bundler thor rvm gem rails3 ruby growl cap ruby github git-flow knife zsh-syntax-highlighting)

# Make Ruby even faster
RUBY_HEAP_MIN_SLOTS=1000000
RUBY_HEAP_SLOTS_INCREMENT=1000000
RUBY_HEAP_SLOTS_GROWTH_FACTOR=1
RUBY_GC_MALLOC_LIMIT=1000000000
RUBY_HEAP_FREE_MIN=500000

# Always use Bundler with RVM.
USE_BUNDLER=force

# Load the DOTS framework
source $DOTS/lib/dots.sh
